# Generated by Django 3.0.8 on 2020-07-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=40)),
                ('door_status', models.BooleanField(default=True)),
                ('uid', models.CharField(max_length=50)),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateField()),
                ('date_time', models.DateTimeField()),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
