# Generated by Django 3.0.8 on 2020-07-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_auto_20200728_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='start_date',
        ),
        migrations.AddField(
            model_name='user',
            name='autorized',
            field=models.BooleanField(default=False),
        ),
    ]
