# Generated by Django 3.0.8 on 2020-07-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0004_auto_20200728_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='uid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
